#!/usr/bin/env bash

# This script enables the Proton VPN permanent kill switch, connects to a Russian server, then displays the status

protonvpn-cli ks --permanent
protonvpn-cli c --cc RU
protonvpn-cli s